name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest

    steps:
      # Étape 1 : Checkout du code du dépôt
      - name: Check out the repo
        uses: actions/checkout@v4

      # Étape 2 : Connexion à Docker Hub en utilisant les identifiants stockés dans les Secrets GitHub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Étape 3 : Construction de l'image Docker en utilisant Docker Compose
      - name: Construction de l'image Docker
        run: |
          docker-compose build -t 'spm-backend'
          docker-compose build -t 'spm-frontend'

        # Étape 4 : Extraction et push des tags des images
      - name: Extraction et push des tags des images
        run: |
          # Extraire les tags des images depuis le fichier docker-compose.yml
          echo docker-compose config
          frontend_image=$(docker-compose config | grep 'image:' | grep 'spm-frontend' | awk '{print $2}')
          backend_image=$(docker-compose config | grep 'image:' | grep 'spm-backend' | awk '{print $2}')

          echo "Frontend Image: $frontend_image"         
          echo "Backend Image: $backend_image"

          # Tag et push des images vers Docker Hub
          if [ -n "$backend_image" ]; then
            docker push $backend_image:latest
          fi

          if [ -n "$frontend_image" ]; then
            docker push $frontend_image:latest
          fi


 