name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest

    steps:
      # Étape 1 : Checkout du code du dépôt
      - name: Check out the repo
        uses: actions/checkout@v4

      # Étape 2 : Connexion à Docker Hub en utilisant les identifiants stockés dans les Secrets GitHub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Étape 3 : Construction de l'image backend
      - name: Construction de l'image backend
        run: |
          docker build -t spm-backend ./backend

      # Étape 4 : Construction de l'image frontend
      - name: Construction de l'image frontend
        run: |
          docker build -t spm-frontend ./frontend

      # Étape 5 : Tag et push des images vers Docker Hub
      - name: Tag et push des images vers Docker Hub
        run: |
          # Taguer les images
          docker tag spm-backend ${{ secrets.DOCKER_USERNAME }}/spm-backend:latest
          docker tag spm-frontend ${{ secrets.DOCKER_USERNAME }}/spm-frontend:latest

          # Pousser les images vers Docker Hub
          docker push ${{ secrets.DOCKER_USERNAME }}/spm-backend:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/spm-frontend:latest