name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest

    steps:
      # Étape 1 : Checkout du code du dépôt
      - name: Check out the repo
        uses: actions/checkout@v4

      # Étape 2 : Connexion à Docker Hub en utilisant les identifiants stockés dans les Secrets GitHub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Étape 3 : Construction de l'image Docker en utilisant Docker Compose
      - name: Construction de l'image Docker
        run: docker-compose build

      # Étape 4 : Pousser l'image Docker vers Docker Hub
      - name: Push de l'image Docker
        run: |
          IMAGE_TAG=$(docker-compose config | grep image: | awk '{print $2}')
          docker tag $IMAGE_TAG $IMAGE_TAG:latest
          docker push $IMAGE_TAG


      # # Étape 3 : Extraction des métadonnées pour Docker (tags, labels)
      # - name: Extract metadata (tags, labels) for Docker
      #   id: meta
      #   uses: docker/metadata-action@v4
      #   with:
      #     images: thetips4you/testjodejsapp

      # # Étape 4 : Construction et push de l'image Docker vers Docker Hub
      # - name: Build and push Docker image
      #   uses: docker/build-push-action@v4
      #   with:
      #     context: .
      #     push: true
      #     tags: ${{ steps.meta.outputs.tags }}
      #     labels: ${{ steps.meta.outputs.labels }}